repos:
  - repo: local
    hooks:
      - id: just-lint-all
        name: just lint-all
        entry: just lint-all
        language: system
        files: \.rs$
        pass_filenames: false
      - id: just-lint-py
        name: just lint-py
        entry: just lint-py
        language: system
        files: \.py$
        pass_filenames: false
      - id: just-lint-java
        name: just lint-java
        entry: just lint-java
        language: system
        files: \.java$
        pass_filenames: false
