edition = "2024"

# Nightly-only
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
wrap_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
