[project]
name = "matcher_py"
version = "1.7.0"
readme = "README.md"
requires-python = ">=3.7"
authors = [{ name = 'Fuji Guo' }, { email = "f975793771@gmail.com" }]
dependencies = ["cffi", "typing-extensions", "msgspec", "numpy"]

[build-system]
requires = ["maturin>=1.1.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
strip = true
profile = "release"
module-name = "matcher_py"
