name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          profile: minimal
          default: true

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install maturin
      run: python3 -m pip install --user --upgrade pip maturin

    - name: Install cmake
      uses: lukka/get-cmake@latest

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.5
      id: install-boost
      with:
          boost_version: 1.73.0

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose