name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          profile: minimal
          default: true

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install maturin
      run: python3 -m pip install --user --upgrade pip maturin

    - name: Install hyperscan
      run: sudo apt install -y libhyperscan-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose