name: Build and Release

on:
  push:
    tags:
      - 'v*'
    paths:
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: so
          - runner: maxos-12
            target: x86_64-apple-darwin
            suffix: dylib
          - runner: macos-14
            target: aarch64-apple-darwin
            suffix: dylib
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.platform.target }}
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: libmatcher
          path: |
            ./target/${{ matrix.platform.target }}/release/libmatcher_c.${{ matrix.platform.suffix }}
            ./target/${{ matrix.platform.target }}/release/libmatcher_py.${{ matrix.platform.suffix }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: libmatcher
          merge-multiple: true
          path: artifact
      - name: Make elease
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: artifact/*