name: rust

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-all-features,cargo-nextest
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo all-features nextest run
        working-directory: matcher_rs
        env:
          RUST_BACKTRACE: 1
      - name: Run doc
        run: cargo doc
        working-directory: matcher_rs
      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo publish -p matcher_rs