name: rust

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - name: Install boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.89.0
      - name: Install cargo-all-features
        run: cargo install cargo-all-features
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo all-features test
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          RUST_BACKTRACE: 1
      - name: Run doc
        run: cargo doc
      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo publish -p matcher_rs
          cargo publish -p matcher_py
          cargo publish -p matcher_c
