name: rust

on:
  push:
    tags: 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          profile: minimal
          default: true

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install maturin
      run: python3 -m pip install --user --upgrade pip maturin

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Publish matcher_rs
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: cargo publish -p matcher_rs