name: rust

on:
  push:
    files:
      - 'matcher_rs/**'
      - '.github/workflows/rust.yml'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            profile: minimal
            default: true
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install maturin
        run: python3 -m pip install --user --upgrade pip maturin
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run doc
        run: cargo doc

  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Publish matcher_rs
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish -p matcher_rs
