name: rust

on:
  push:
    paths:
      - 'matcher_c/src/**'
      - 'matcher_py/src/**'
      - 'matcher_rs/src/**'
      - '.github/workflows/rust.yml'
  pull_request:
    paths:
      - 'matcher_c/src/**'
      - 'matcher_py/src/**'
      - 'matcher_rs/src/**'
      - '.github/workflows/rust.yml'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests prebuilt
        run: cargo test -p matcher_rs --verbose --no-default-features --features "prebuilt"
      - name: Run tests runtime_build
        run: cargo test -p matcher_rs --verbose --no-default-features --features "runtime_build"
      - name: Run tests serde
        run: cargo test -p matcher_rs --verbose --features "serde"
      - name: Run doc
        run: cargo doc
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo publish -p matcher_rs
          cargo publish -p matcher_py
          cargo publish -p matcher_c
