name: rust

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test -p matcher_rs --verbose --no-default-features
      - name: Test dfa
        run: cargo test -p matcher_rs --verbose --no-default-features --features "dfa"
      - name: Test runtime_build and dfa
        run: cargo test -p matcher_rs --verbose --no-default-features --features "runtime_build,dfa"
      - name: Test serde and dfa
        run: cargo test -p matcher_rs --verbose --no-default-features --features "serde,dfa"
      - name: Run doc
        run: cargo doc
      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo publish -p matcher_rs
          cargo publish -p matcher_py
          cargo publish -p matcher_c
